/**
 * Pure maths for the hand-rolled SVG charts.
 *
 * Pane deliberately ships no charting library — see AGENTS.md. Keeping the
 * scale/tick/arc maths here means it can be unit-tested without a DOM, and the
 * chart components stay thin presentational wrappers.
 */

/** Map a value from a data domain onto a pixel range. */
export function linearScale(value: number, domainMin: number, domainMax: number, rangeMin: number, rangeMax: number): number {
  if (domainMax === domainMin) return rangeMin;
  const t = (value - domainMin) / (domainMax - domainMin);
  return rangeMin + t * (rangeMax - rangeMin);
}

/**
 * Round a raw step up to the next "nice" number (1, 2, 5, 10 x 10^n), so axis
 * labels land on values a human would have chosen.
 */
function niceStep(rawStep: number): number {
  if (rawStep <= 0) return 1;
  const magnitude = 10 ** Math.floor(Math.log10(rawStep));
  const normalized = rawStep / magnitude;
  if (normalized <= 1) return magnitude;
  if (normalized <= 2) return 2 * magnitude;
  if (normalized <= 5) return 5 * magnitude;
  return 10 * magnitude;
}

/**
 * Evenly spaced axis ticks covering `[0, max]`.
 *
 * Always returns at least two ticks so an axis is never a single label, and
 * handles a zero or negative max (an empty chart) by returning `[0, 1]`.
 */
export function niceTicks(max: number, targetCount = 4): number[] {
  if (!Number.isFinite(max) || max <= 0) return [0, 1];

  const step = niceStep(max / Math.max(targetCount, 1));
  // Extend to the first step at or above max, so the top tick always covers
  // the data. Ticks are generated by index to avoid accumulating float error.
  const stepCount = Math.max(Math.ceil(max / step), 1);

  const ticks: number[] = [];
  for (let i = 0; i <= stepCount; i++) {
    ticks.push(Number((i * step).toFixed(10)));
  }
  return ticks;
}

/** Upper bound of an axis: the smallest nice tick at or above `max`. */
export function niceMax(max: number, targetCount = 4): number {
  const ticks = niceTicks(max, targetCount);
  return ticks[ticks.length - 1];
}

/**
 * SVG path for a donut segment.
 *
 * `startFraction` and `endFraction` are 0..1 of a full turn, measured
 * clockwise from 12 o'clock. Fractions are clamped, so a caller that computes
 * slightly over 1 from floating-point error still renders.
 */
export function arcPath(
  cx: number,
  cy: number,
  outerRadius: number,
  innerRadius: number,
  startFraction: number,
  endFraction: number
): string {
  const start = Math.min(Math.max(startFraction, 0), 1);
  const end = Math.min(Math.max(endFraction, 0), 1);
  if (end <= start) return '';

  // A full circle cannot be drawn with a single arc — two halves are needed.
  if (end - start >= 1) {
    return [
      arcPath(cx, cy, outerRadius, innerRadius, 0, 0.5),
      arcPath(cx, cy, outerRadius, innerRadius, 0.5, 1),
    ].join(' ');
  }

  const toPoint = (fraction: number, radius: number) => {
    const angle = fraction * Math.PI * 2 - Math.PI / 2;
    return { x: cx + Math.cos(angle) * radius, y: cy + Math.sin(angle) * radius };
  };

  const largeArc = end - start > 0.5 ? 1 : 0;
  const outerStart = toPoint(start, outerRadius);
  const outerEnd = toPoint(end, outerRadius);
  const innerEnd = toPoint(end, innerRadius);
  const innerStart = toPoint(start, innerRadius);

  return [
    `M ${outerStart.x} ${outerStart.y}`,
    `A ${outerRadius} ${outerRadius} 0 ${largeArc} 1 ${outerEnd.x} ${outerEnd.y}`,
    `L ${innerEnd.x} ${innerEnd.y}`,
    `A ${innerRadius} ${innerRadius} 0 ${largeArc} 0 ${innerStart.x} ${innerStart.y}`,
    'Z',
  ].join(' ');
}

/** Compact token counts: 1200 -> "1.2K", 3_400_000 -> "3.4M". */
export function formatTokens(value: number): string {
  if (!Number.isFinite(value)) return '0';
  const abs = Math.abs(value);
  if (abs >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(1)}B`;
  if (abs >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`;
  if (abs >= 1_000) return `${(value / 1_000).toFixed(1)}K`;
  return String(Math.round(value));
}

/** Cost formatting that stays informative for very small amounts. */
export function formatUsd(value: number): string {
  if (!Number.isFinite(value) || value === 0) return '$0.00';
  if (Math.abs(value) < 0.01) return '<$0.01';
  return `$${value.toFixed(2)}`;
}
